### ISSUE TITLE
run command get an error

### ISSUE THREAD

**Issue by suncodeer** [react-native-community/react-native-template-typescript#101]
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript
: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\i321872\\Desktop\
\rn-2\\rnts02\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.12.3
[1/2] Removing module react-native-template-react-native-template-typescript...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript. This
 is not a critical error, you can work on your app.
(node:30872) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-templa
te-typescript
    at makeError (C:\Users\i321872\Desktop\rn-2\rnts02\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\i321872\Desktop\rn-2\rnts02\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 3)
(node:30872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by radko93** [comment]
Please read [usage](https://github.com/react-native-community/react-native-template-typescript#arrow_forward-usage), you cannot add this library to your app.
