### ISSUE TITLE
Command not found: react-native

### ISSUE THREAD

**Issue by efecantekin** [react-native-community/react-native-template-typescript#104]
After react-native init with NPX, when I run "react-native run-ios" command it gives an error as "react-native run-ios 
zsh: command not found: react-native"

I understand that I have this problem because I initialized React-Native with NPX. I can run simulator with adding NPX head of the command. If there is any other solution, I think we might update read me file about the usege with NPX.

**Comment by MateusAndrade** [comment]
You tried running a: ```yarn ios``` or ```npm run ios```?

**Comment by efecantekin** [comment]
I tried `npm run iOS` and also already know the goal of package.json but forgot that I initialized the project with NPX. I remembered it after 2-3 tryings later. It will be nice if readme file includes the knowledge about that.

**Comment by radko93** [comment]
You can just install the new cli `yarn add -D @react-native-community/cli` and it should work again. If you feel it's a problem please open an issue on CLI repo.
