### ISSUE TITLE
Typescript validation is not working in VSCode.

### ISSUE THREAD

**Issue by maxkalik** [react-native-community/react-native-template-typescript#116]
# How to enable validation in VSCode?

After initiating a new project I expected to see eslint / tslint validation in VSCode. But even my auto-correction doesn't work. VSCode message: "Failed to apply ESLint fixes to the document. Please consider opening an issue with steps to reproduce."
I checked JSON settings, installed TSLint extension. But anyway it seems to be some problem with validation.
What I did wrong? Should I set up something additional? Thanks!

**Comment by MateusAndrade** [comment]
This looks related to your specific VS Code install. Did you tried a fresh install of it?

**Comment by maxkalik** [comment]
@MateusAndrade It's the freshest version of VS Code. Also, there is an enabled extension TSLint. Maybe because of this? But I tried to disable it.

**Comment by MateusAndrade** [comment]
> @MateusAndrade It's the freshest version of VS Code. Also, there is an enabled extension TSLint. Maybe because of this? But I tried to disable it.

Probably it's related to TSlint, since it's now deprecated: https://github.com/palantir/tslint#tslint.

You can try removing that extension, and using another.

**Comment by dantasfiles** [comment]
@MateusAndrade I use VSCode on Windows.
My setup is 
```
Id: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 2.0.15
Publisher: Dirk Baeumer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
```
and
```
Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 3.20.0
Publisher: Esben Petersen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
```

With those two extensions installed, everything (linting, type-checking, prettying) just kind of works.

**Comment by maxkalik** [comment]
Hey. Sorry for the late answering. I removed extension TSLint and it helped!

**Comment by MateusAndrade** [comment]
Since it looks that your problem has been solved, i'm closing this issue @maxkalik. 🎉
