### ISSUE TITLE
Index module (index.js now) should be also on typescript.

### ISSUE THREAD

**Issue by Enuvid** [react-native-community/react-native-template-typescript#121]
# Feature Request

Index module (index.js now) should be also on the typescript (_.ts_ file). Currently, this file is _js_ file and i think it's a not best idea and not much consistency in the template for typescript. 

I am not saying that this really should be so. Perhaps there are reasons why this is a _.js_ file. However, I tried to change locally and did not encounter any problems.

## Why it is needed

I also checked the [typescipt template of _create-react-app_](https://github.com/facebook/create-react-app/tree/master/packages/cra-template-typescript/template/src) and there also used .ts{x} extension of 'index' file.

#
I will be glad to create PR if the proposal is accepted.

**Comment by emin93** [comment]
Thanks for bringing this up. I remember when I tried it a while ago, it didn't work because on iOS the path was defined specifically to the `.js` file. But maybe that has changed in the meantime. If you can confirm that it works on iOS and Android, feel free to create a PR 🙂

**Comment by Naturalclar** [comment]
I believe the entry point stills needs to be `.js` as there is no support for any other language extentions at this point
ref: https://github.com/facebook/react-native/pull/27491

**Comment by Enuvid** [comment]
Make sense, thank you:)

**Comment by FDiskas** [comment]
I renamed and it worked if I specified env variable
```
ENTRY_FILE=index.ts
```
