### ISSUE TITLE
How do I debug apps built using this template

### ISSUE THREAD

**Issue by ArthurHNL** [react-native-community/react-native-template-typescript#122]
# Question

Hello, I have been trying to get debugging to work in both VSCode and the React Native Chromium debugger, without any success. Is there any documentation on how to debug an application built using this template?

**Comment by Naturalclar** [comment]
For debugging React Native App, you can use the standalone version of React Devtools.
More information can be found at https://reactnative.dev/docs/0.60/debugging
There is also a tool called Flipper https://github.com/facebook/flipper that can be used to debug both native side and react codes.

**Comment by ArthurHNL** [comment]
Thanks a lot, that works. Any idea on how I can get VSCode to debug the app?

**Comment by ArthurHNL** [comment]
I figured it out, using the [React Native extension provided by Microsoft](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native), you can attach to a packager that has been launched **using the React Native extension**, using the following launch.json configuration:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to packager",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "attach",
            "sourceMaps": true
        }
    ]
}
```

(The key is to set '`sourceMaps`' to '`true`')
