### ISSUE TITLE
How to avoid tsconfig error: 'noEmit' cannot be specified with option 'incremental'. 

### ISSUE THREAD

**Issue by rphovley** [react-native-community/react-native-template-typescript#124]
When using this template, out of the box, we get an error in our tsconfig that says: Option 'noEmit' cannot be specified with option 'incremental'. 

This error shows up in the Typescript Github conversation here:
https://github.com/microsoft/TypeScript/issues/33809#issuecomment-589446027

The template comes with both options `noEmit` and `incremental` specified which is not supported. Essentially, from what I've read, if you supply `noEmit` as an option, `incremental` doesn't do anything for you (because it uses the emitted files that you are specifying to no longer emit). 

I am curious if there's a reason maybe outside of the existing conversation on this thread I mentioned above as to why both options are specified? 

For us it's more an annoyance at this point since it doesn't affect our builds but I'd still like to understand if maybe there's something we're missing?  I think if both options are supposed to be included, it'd be nice to have somewhere this is referenced in the docs and how to quiet the error.

**Comment by MR03web** [comment]
I commented "incremental",No problems found yet

**Comment by rphovley** [comment]
Yeah, I think we will likely do the same if there isn't any other reasons provided

**Comment by emin93** [comment]
Seems like this has been added only for performance improvements in the following PR: https://github.com/react-native-community/react-native-template-typescript/pull/100

I'd suggest we revert this commit as incremental compilation doesn't work anyway when there's no emitted output. What do you think @radko93?

**Comment by emin93** [comment]
Fixed in [6.3.16](https://github.com/react-native-community/react-native-template-typescript/releases/tag/6.3.16) 🙂
