### ISSUE TITLE
TS 3.8 is used, but does not work.

### ISSUE THREAD

**Issue by Guuz** [react-native-community/react-native-template-typescript#130]
# Bug

The latest version of this template uses Typescript 3.8.3. TS 3.8 has a few new features: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**For instance the "Top-Level await" feature does not work using this template. The template should either not use TS 3.8 or make sure all features work.**

![image](https://user-images.githubusercontent.com/810327/78575070-23eec980-782b-11ea-8ec7-5cb305ccc50a.png)
![image](https://user-images.githubusercontent.com/810327/78575088-294c1400-782b-11ea-9d91-7379faa5bd84.png)

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 103.57 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps To Reproduce

1. npx react-native init MyApp --template react-native-template-typescript
2. Copy top level await example from https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html to App.tsx
...

Describe what you expected to happen:

1. TS 3.8 features to work

## Reproducible sample code

not needed i think since the repo steps are so simple.

**Comment by radko93** [comment]
Did you change your TSconfig to suggested in the error?

**Comment by Guuz** [comment]
Yes. you can fix the IDE error by changing the TS config. This would be "bug 1" since this template should do this for me. The template now gives the user a "not working" end result.

But even if you fix the TSC side, Babel or RN (not sure where it goes wrong) doesn't seem to support these features yet. Or the config is wrong. See the second error when running the code on device. This still happen with the following TS config:
![image](https://user-images.githubusercontent.com/810327/78681368-efdbdd00-78ec-11ea-853e-599c2533d713.png)

**Comment by radko93** [comment]
@Guuz this is unfortunately not possible to do fix for us as it's related to the metro bundler https://github.com/facebook/metro/issues/522

**Comment by Guuz** [comment]
Ok. no problem, i understand.

But is this template not "bugged" then? shouldn't we put 3.7 in the template instead of 3.8? I would expect this template to give me a working TS + RN project. This could be a pitfall for new users.

**Comment by radko93** [comment]
That's a valid point. But then some of the features in 3.8 might work? But I will consider downgrading to 3.7 temporary.

**Comment by Guuz** [comment]
I'll leave that decision up to you! :) you can close this issue if you want. It has served its purpose i think.
