### ISSUE TITLE
Template-Address not found

### ISSUE THREAD

**Issue by xstable** [react-native-community/react-native-template-typescript#132]
If I use the suggested command-line, I got this Error: 

![image](https://user-images.githubusercontent.com/1778068/78993504-1ba1d180-7b3e-11ea-9b01-bec51cded762.png)

**Comment by rdev** [comment]
Try `--template typescript`

**Comment by radko93** [comment]
check https://github.com/react-native-community/react-native-template-typescript/issues/80
