### ISSUE TITLE
npx react-native init MyApp --template react-native-template-typescript DOESN'T WORK

### ISSUE THREAD

**Issue by kotpal** [react-native-community/react-native-template-typescript#134]
> npx react-native init MyApp --template react-native-template-typescript
> cd MyApp
> yarn start

And then browsing to http://localhost:8081

> React Native packager is running.
> Visit documentation

What is happening? How can I just a react-native with TypeScript just get to work?

**Comment by radko93** [comment]
Seems like you didn't started the app. React Native does not work in the browser, you need to run the app on the simulator. Follow the guide here https://reactnative.dev/docs/environment-setup
