### ISSUE TITLE
Using asynchronous iterators

### ISSUE THREAD

**Issue by raffaeler** [react-native-community/react-native-template-typescript#135]
# Question

Asynchronous iterators and generators (aka `await for ... of`) are available as part of ES2018.
Example:
```
// generator
 async function* gen() {
     yield 'a';
     yield 'b';
     return 2;
 }

// consumer
try {
    for await (const t of gen()) {
        console.log(t)
    }
}
catch(err) {
    console.log("err", err);
}
```

The template already specify esnext generation with target. I also added esnext to lib but still the feature cannot be used:
```
    "target": "esnext",
    "module": "commonjs",
    "lib": [ "es6", "esnext"], 
     ...
```

Questions:
- which version of ES is yhe template supposed to work with?
- where can I find a working example using `for await of` (possibly in typescript)?

Thanks!

**Comment by radko93** [comment]
Hey, can you make sure you fulfil all the things from the list of requirements here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#the-for-await-of-statement

**Comment by raffaeler** [comment]
Sure I did. You can see the example I posted comes from there.
When I first started, the non-async iterators did not work as well. Then I added this and they worked.
```
var Symbol = require("es6-symbol");
``` 

Other tests I made:
1. using the basic polyfill suggested in the typescript website:
```
(Symbol as any).asyncIterator = Symbol.asyncIterator || Symbol.for("Symbol.asyncIterator");
```

2. trying to update `core-js`

Do you know any basic example where `await for of` is working? This is a construct that could dramatically simplify the code I am working on.

Thank you

**Comment by radko93** [comment]
I think the issue here like in #130 is that metro does seem to support it. If this is not strictly related to TS (does not seem to be as it's also a ES2018 feature) I would recommend opening issue on metro with this problem.

**Comment by raffaeler** [comment]
@radko93 I don't get how this issue would depend on metro.
With regards to that issue, I never had problems using async/await ... they perfectly work in my projects (I always started from the plain typescript template).

I am afraid my problem can be related to either the tsconfig or the assortment of the dependant libraries instead.

**Comment by radko93** [comment]
@raffaeler if this will work in plain RN project then it's an issue with the template (this is possible to check as it's not a TS exclusive feature). The reason I'm thinking that metro is not supporting this is that Typescript files in React Native are not really compiled to JS, but instead, Metro (with babel) transpile ts files to JS. So whatever happens with your code it's related only to Metro. That's why #130 does not work even if the user has installed 3.8 which should support this feature, but Metro cannot understand this. So I suspect it's the same with this issue.

**Comment by raffaeler** [comment]
Got it, it makes sense. I will close this for now and see if someone in the metro repo will answer. I posted there in the past but it looks like a desert.
Thanks
