### ISSUE TITLE
[Feature Request] Initialize window.rootViewController as a UINavigationController

### ISSUE THREAD

**Issue by JonatanSalas** [react-native-community/react-native-template-typescript#142]
# Feature request

Making `window.rootViewController` be initialized as a `UINavigationController`. 

## Why it is needed

The 2 motivations for this change are:

- **It's a burden for new-comers to interact with objective-c**
- Some IOS native SDKs that integrate native view controllers need a UINavigationController for its initialization. 

For e.g, `MercadoPago` which is a payment platform from Latam has a [native SDK for IOS](https://github.com/mercadopago/px-ios#3---start) that needs to be initialized with a `UINavigationController`

## Possible implementation

This change implies adding the following code in the `AppDelegate`: 

```diff
+ UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:rootViewController];
+ [navController setToolbarHidden:YES animated:YES];
+ [navController setNavigationBarHidden:YES];

-  self.window.rootViewController = rootViewController;
+ self.window.rootViewController = navController;
```

### Code sample

Here is a [working example](https://github.com/BlackBoxVision/react-native-mercadopago-px/blob/master/example/ios/ReactNativeMercadopagoPxExample/AppDelegate.m#L29).

**Comment by radko93** [comment]
Hi! Unfortunately, I will have to redirect you to the main RN repo https://github.com/facebook/react-native. This template only copies native code from RN template and adds some TS configuration. So it has to be changed over there first.

**Comment by JonatanSalas** [comment]
@radko93 sorry! I didn't notice that, my bad! thanks for your response!!
