### ISSUE TITLE
Release v6.5.2 custom fonts error.

### ISSUE THREAD

**Issue by Shadaw** [react-native-community/react-native-template-typescript#145]
# Bug report

## Summary

I'm trying install custom fonts in react native, but result im this error.
running `npx react-native link` or `yarn react-native link` fails with:
```bash
info Linking assets to ios project
error Linking assets failed. Run CLI with --verbose flag for more details.
SyntaxError: Expected [\n\r] but end of input found.
  at peg$buildStructuredError (<project_name>\node_modules\xcode\lib\parser\pbxproj.js:429:12)
```

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-4430S CPU @ 2.70GHz
    Memory: 1019.87 MB / 7.91 GB
  Binaries:
    Node: 12.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 1.8.0_211 - /c/Program Files/Java/jdk1.8.0_211/bin/javac
    Python: 2.7.16 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.5.2

## Steps to reproduce

1. create `assets/fonts` folder in project root.
2. add fonts in fonts folder.
3. create `react-native.config` file.
4. run `npx react-native link` or `yarn react-native link`.

## Reproducible sample code

`folders`
```
...
assets
--fonts
----RobotoSlab-Medium.ttf
----RobotoSlab-Regular.ttf
...
react-native.config.js
```

`react-native.config.js`
```js
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./assets/fonts']
};
```

**Comment by Bruno-hub19** [comment]
Same problem here :cry:

**Comment by yepMad** [comment]
Same problem here, with these same fonts. Maybe the npx/yarn react-native link stops in iOS if you haven't a iOS project.

**Comment by yepMad** [comment]
Same problem here, with these same fonts. Maybe the npx/yarn react-native link stops in iOS if you haven't a iOS project.

### Partial solution:

- Create a folder / assets / fonts in the path ./android/app/src/main.
So getting: **./android/app/src/main/assets/fonts**

![Screenshot_1](https://user-images.githubusercontent.com/22564368/88384307-87711880-cd82-11ea-8666-d9e66e4c491f.png)

**Comment by radko93** [comment]
Is this related to this template? I think it's related to https://github.com/react-native-community/cli

**Comment by daanielcruz** [comment]
It can be solved just adding a new line to end of ios/[Project].xcodeproj/project.pbxproj  :raised_hands:

**Comment by Shadaw** [comment]
working in 6.5.5
