### ISSUE TITLE
Link Assets 0.63.0 typescript template

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [react-native-community/react-native-template-typescript#146]
# Bug report

## Summary

Hi, I create new RN Project with command  `npx react-native init AwesomeTSProject --template react-native-template-typescript` then add font in `src/assets/fonts` and want to link fonts with `npx react-native link`

## Environment info

`react-native info` output:

```bash
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
    Memory: 362.99 MB / 7.76 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.5.2

## Steps to reproduce

1.init new project with `npx react-native init AwesomeTSProject --template react-native-template-typescript`
2.add fonts in src/assets/fonts
3.add `react-native.config.js` file with :
```
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: ['./src/assets/fonts/'],
};
```
4. run `npx react-native link`
Describe what you expected to happen:

Link font for android and ios 

## Reproducible sample code

![Screenshot from 2020-07-15 21-19-53](https://user-images.githubusercontent.com/37307562/87575782-ac5fee80-c6e5-11ea-936d-2e8a085100f1.png)

**Comment by MadaShindeInai** [comment]
same problem.  I have no errors but fonts do not work on android device or simulator.  Check all guides try all combinations.

**Comment by radko93** [comment]
If this does not work please open an issue on the react native CLI repo, this template is not related to how this works.
