### ISSUE TITLE
package.json inside the template folder creates build time error

### ISSUE THREAD

**Issue by sangiliarumugam** [react-native-community/react-native-template-typescript#154]
**I get the below error in Metro**

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/sangili/Projects/npxnative/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/sangili/Projects/npxnative/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 2) {
  mockPath1: 'package.json',
  mockPath2: 'template/package.json'
}
Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/sangili/Projects/npxnative/node_modules/jest-haste-map/build/index.js:620:17)

**I can able to fix this by removing the package.json file inside the template folder.**

**Comment by radko93** [comment]
But how do use this template? You should not clone this repo directly.

**Comment by sangiliarumugam** [comment]
I used react-native init myApp --template=typescript to create a new project and the boilerplate code contains two package.json files.

**Comment by emin93** [comment]
Please make sure to use it as described in the `README.md`.

First uninstall the old deprecated CLI: https://github.com/react-native-community/react-native-template-typescript#note-on-the-legacy-cli

And then run `npx react-native init MyApp --template react-native-template-typescript`.

**Comment by sangiliarumugam** [comment]
Thanks. It worked.
