### ISSUE TITLE
Template is broken and does not run

### ISSUE THREAD

**Issue by luskin** [react-native-community/react-native-template-typescript#155]
# Bug report

## Summary

All we did was run the command: `npx react-native init MyApp --template react-native-template-typescript`
we `cd`'d into the directory, did a `yarn start` in one terminal and and a `yarn ios` in another terminal. We didn't touch a single line of code, and we get these errors:

```
Check your code at renderApplication.js:45.
[Mon Aug 03 2020 19:22:33.172]  ERROR    Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

This error is located at:
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 42.43 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps to reproduce

1. Follow typescript install steps
2. run app

Describe what you expected to happen:

1. App to run without error

**Comment by kozillla** [comment]
yup exac same... 
Looks like it tries to pull from wrong URL, in logs can see : 

```error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".```

**Comment by jtich** [comment]
Have you tried including the npx flag `--ignore-existing`? It ensures npx uses the latest and greatest. I'd try something like:
`npx --ignore-existing react-native init AppName --template react-native-template-typescript`

**Comment by maeneak** [comment]
> Have you tried including the npx flag `--ignore-existing`? It ensures npx uses the latest and greatest. I'd try something like:
> `npx --ignore-existing react-native init AppName --template react-native-template-typescript`

Worked for me 👍

**Comment by anthonytietjen** [comment]
Worked for me too. Thanks for sharing this.

**Comment by emin93** [comment]
Closing this as this seems to be related to the old CLI.
