### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by nusendra** [react-native-community/react-native-template-typescript#158]
When i install this template through this command

`npx react-native init MyApp --template react-native-template-typescript`

it failed

![image](https://user-images.githubusercontent.com/8466308/91686373-50630380-eb87-11ea-9704-74319f179014.png)

---

but if i use this command

`npx react-native init MyApp --template typescript`

its now working fine. Please fix this issue thanks :)

**Comment by radko93** [comment]
Make sure to check out this issues https://github.com/react-native-community/react-native-template-typescript/issues/80
