### ISSUE TITLE
rename/alias the template

### ISSUE THREAD

**Issue by ofirgeller** [react-native-community/react-native-template-typescript#163]
# Feature request and why it is needed

Can we rename it to just 'typescript'? since both 'react-native' and template are redundant.

**Comment by trangcongthanh** [comment]
I thing under the hood, cli will fetch `react-native-template-typescript` package or the custom template package name. If you want to use typescript only, so the cli need to hardcode the `react-native-template-`. And it'll not allow other guys create custom template under their npm organization. Ex: `@myorg/rn-template`

If you look the init command too ugly, you can alias it in your .bashrc or .zshrc. It'll better than change cli code and rename current react-native-template-typescript npm package.

**Comment by ofirgeller** [comment]
Not sure I understand you completely, 

Currently this command

`react-native init myApp --template react-native-template-typescript`

works, but:

`react-native init myApp --template typescript`

fails with:
" Error: Couldn't find the "<my temp folder>\rncli-init-template-gfnFHp\node_modules\typescript\template.config.js file inside "typescript" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template"

Looking at the react-native-cli code it seems like the second command should work, as 'react-native-template' is added as a prefix to the template name parameter:

https://github.com/react-native-community/cli/blob/c23e16192f8d23915c14a11e54c3d5ffdfb243df/packages/cli/src/tools/generator/templates.ts#L62

So unless I have some local issue there is a setup bug in this repo or there is a bug in the cli code, I can see this project has a 'template.config.js', (also i'm thinking without it the first command would fail), but maybe the cli, which is looking for the file under the short name ('typescript') is installing the package into the long name and then not finding it.

**Comment by trangcongthanh** [comment]
I thing init command with template using this
https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/init/template.ts

**Comment by emin93** [comment]
👋 @ofirgeller 

> Can we rename it to just 'typescript'?
No, because it needs to be published to npm with that name and obviously `typescript` is already taken.

> Looking at the react-native-cli code it seems like the second command should work
The code that you referenced is from the old CLI. In the new CLI it has been decided to not prepend `react-native-template-` anymore. So this template is called like this because it has been originally created for the old CLI and hasn't been renamed since. I'd suggest to leave it as it is for now because many people are you used to it and there is a lot of documentation that uses it like this.
