### ISSUE TITLE
Immediate failure?

### ISSUE THREAD

**Issue by alexmcmillan** [react-native-community/react-native-template-typescript#175]
## Expected results

node v15.1.0
npm v7.0.8
yarn v1.22.10
react-native v0.63.3

```
> npx react-native init MyApp --template react-native-template-typescript
     ... success without warn/err ...
> cd MyApp
> yarn android
```

Expected to see the react-native default app fire up on my dev device, but instead see errors indicating a lack of support for es6?

## Observed results

Dev device shows error:

```
Unexpected identifier 'Header'.  import call expects exactly one argument.
Unexpected identifier 'Header'.  import call expects exactly one argument.
no stack
no stack
```

Upon opening the developer menu and selecting "Debug", the error page changes to:

```
com.facebook.react.common.JavascriptException: Cannot use import statement outside a module
Cannot use import statement outside a module

loadBundle
WebsocketJavaScriptExecutor.java:162

run
NativeRunnable.java

handleCallback
Handler.java:883

dispatchMessage
Handler.java:100

dispatchMessage
MessageQueueThreadHandler.java:27

loop
Looper.java:237

run
MessageQueueThreadImpl.java:226

run
Thread.java:919
```

### Logs

Please add the log output here.

## Steps to reproduce

1. Init an app as documented and try running on Android with `yarn android`.

**Comment by alexmcmillan** [comment]
Seems to be happening regardless of which template I specify.

**Comment by Arslan106** [comment]
how did you fix that becuase getting the same issue since last week and still no solution found yet you can see [here](https://github.com/facebook/react-native/issues/32888)

**Comment by marciodajr** [comment]
https://github.com/facebook/react-native/issues/32888#issuecomment-1024901374

**Comment by younasm** [comment]
i have the same issue need help! I am using expo.

this is my package.json

`{
  "name": "donewithit",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "7.1.3",
    "@react-navigation/bottom-tabs": "^5.4.4",
    "@react-native-community/hooks": "^2.8.1",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/native-stack": "^5.0.4",
    "@react-navigation/stack": "^5.3.5",
    "apisauce": "^1.1.1",
    "expo": "~44.0.0",
    "expo-constants": "^13.0.2",
    "expo-image-picker": "~12.0.1",
    "expo-location": "~14.0.1",
    "expo-permissions": "~13.1.0",
    "expo-status-bar": "~1.2.0",
    "formik": "^2.1.4",
    "lottie-react-native": "5.0.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "7.12.9"
  },
  "private": true
}
`
