### ISSUE TITLE
pod failing on creating app

### ISSUE THREAD

**Issue by 2manoj1** [react-native-community/react-native-template-typescript#176]
## Expected results

What did you expect to happen?
app should create

## Observed results

What happened?
✖ Installing CocoaPods dependencies (this may take a few minutes)
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./Mobileapp/ios && pod install".
CocoaPods documentation: https://cocoapods.org/
### Logs

Please add the log output here.

## Steps to reproduce

npx react-native init Mobileapp --template react-native-template-typescript

**Comment by radko93** [comment]
Can you try if creating a react native project without the template will work for you? If it does not then the issue is not related to the template.

**Comment by 2manoj1** [comment]
Same issue. I found that its happening inside monorepo. Solution (workaround) - create or init app outside of monorepo and copy and link with monorepo.

**Comment by radko93** [comment]
I will close this. If you have trouble like this you can open an issue on the cli repo.
