### ISSUE TITLE
Latest version not found on npm

### ISSUE THREAD

**Issue by Simon-TechForm** [react-native-community/react-native-template-typescript#178]
## Expected results

To find the latest version (v6.5.9 as of today) of this pacakge on npmjs.com

## Observed results

Found v6.5.7

It would be nice to have the latest version published to npm, to include the latest RN version in new projects. (I'm aware that I can manually clone and point to the package as a workaround :) ).

**Comment by emin93** [comment]
It seems the release pipeline didn't work for a while because `npm test` exits with code 1 instead of 0 when there is no test script defined. Fixed now, had to release twice to test, so the latest version 6.5.11 is now also released on npm.

**Comment by Simon-TechForm** [comment]
Thank you 👍
