### ISSUE TITLE
update eslint-config to v2.0.0

### ISSUE THREAD

**Issue by jahead** [react-native-community/react-native-template-typescript#183]
Hey,
Is it possible to get eslinit-config to be on v2.0.0 so we get v7 of eslint?

I don't mind doing the PR, if it's something that's open to a PR

**Comment by Naturalclar** [comment]
> I don't mind doing the PR, if it's something that's open to a PR

That would be great!

**Comment by jahead** [comment]
Hey, 

I'm a bit confused on how this works, but. Following this comment
https://github.com/react-native-community/react-native-template-typescript/pull/184#issuecomment-783301958

however, react-native master has already the respective files updated. 
@emin93 maybe you could move the files over now?

**Comment by emin93** [comment]
If master has the updated versions, then it will likely be in the next RN release and we will move it over here when that happens.

**Comment by radko93** [comment]
It was updated in #193
