### ISSUE TITLE
meu ubuntu nao cria com template Typescript

### ISSUE THREAD

**Issue by jhonatan-JS** [react-native-community/react-native-template-typescript#187]
## Expected results

What did you expect to happen?

## Observed results

What happened?

### Logs

Please add the log output here.

## Steps to reproduce

1.
poderia me ajudar, dar uma dica, ja tentei n maneiras

**Comment by emin93** [comment]
Hi there, I can't see what the issue is here and a Google Translate wasn't helpful either. Closing this unless you can provide more useful information.
