### ISSUE TITLE
Recommended Usage

### ISSUE THREAD

**Issue by jrigert** [react-native-community/react-native-template-typescript#188]
# Question

Hi all, thanks for all the work on this! I wasn't sure where else to ask this...

Do you have a recommended flow/usage for type checking? I was at first expecting this to be part of `npm start`, during compilation, similar to how the `create-react-app` project is set up (non-React Native), where you will get errors right in your node server while developing. But then I read that Babel doesn't do this, I'm not sure how the create-react-app environment has configured this to happen.

So for now, I changed my `npm start` to: `"concurrently --raw \"tsc --watch\" \"react-native start\""`. This is working pretty well, though it has some strange behavior like type checking `node_modules` even though I have that as `exclude` in `tsconfig` (I fixed this by setting to `skipLibCheck` to `true` but I don't fully understand that flag). I also added `tsc` to a pre-commit hook.

Anyway, is this how you would recommend type checking, or is there a better way? Or am I totally missing some functionality of this template? 😄  Any advice would be greatly appreciated, thanks!

**Comment by radko93** [comment]
Hey, thanks your for kind words.

You don't need to run `tsc` when starting the app. This typescript integration only checks for type errors, its not supposed to compile TS. You should use it with your IDE (like vscode) when developing or run from terminal `tsc --no-emit`.

**Comment by jrigert** [comment]
@radko93 Thanks for the quick reply! Yea, I was just talking about the type checking, not compiling. I only added it to `npm start` so that it's always there and I don't forget. Cool, I really just wanted to verify that manually running `tsc` is the way to go, or if there was something else.

Thanks so much!
