### ISSUE TITLE
 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-typescript - Not found

### ISSUE THREAD

**Issue by anuragarwalkar** [react-native-community/react-native-template-typescript#191]
## Expected results
It should clone the typescript template (boilerplate) 

What did you expect to happen?

## Observed results

What happened?

### Logs
info Setting up new React Native app in /home/anurag/Documents/personal_projects/MyApp
info Fetching template react-native-template-react-native-template-typescript...
(node:37349) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-typescript - Not found
npm ERR! 404 
npm ERR! 404  'react-native-template-react-native-template-typescript@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anurag/.npm/_logs/2021-03-10T20_49_44_526Z-debug.log
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 768 packages, and audited 1487 packages in 14s

63 packages are looking for funding
  run `npm fund` for details

7 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
(node:37349) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --save --save-exact react-native-template-react-native-template-typescript
    at makeError (/home/anurag/Documents/personal_projects/MyApp/node_modules/execa/index.js:174:9)
    at /home/anurag/Documents/personal_projects/MyApp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createFromRemoteTemplate (/home/anurag/Documents/personal_projects/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:115:5)
    at async createProjectFromTemplate (/home/anurag/Documents/personal_projects/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/home/anurag/Documents/personal_projects/MyApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:118:3)
    at async Object.initCompat (/home/anurag/Documents/personal_projects/MyApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:105:3)
(node:37349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:37349) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please add the log output here.

## Steps to reproduce
just run the npx react-native init MyApp --template react-native-template-typescript
1.

**Comment by radko93** [comment]
You are unfortunately using a wrong CLI version. Please uninstall it and try to use the new one.
More details: https://github.com/react-native-community/react-native-template-typescript#note-on-the-legacy-cli and #80 (comment)
