### ISSUE TITLE
Error with "npx react-native init AwesomeTSProject"

### ISSUE THREAD

**Issue by vaidehikr** [react-native-community/react-native-template-typescript#202]
## Expected results
Issues  running command "npx react-native init AwesomeTSProject"
What did you expect to happen?
Expected project "AwesomeTSProject" is craeted 
## Observed results
Got error 
What happened?
C:\Users\username\Documents\node-v14.10.0-win-x64>npx react-native init AwesomeProject
npm ERR! code E403
npm ERR! 403 403 MediaTypeBlocked - GET https://registry.npmjs.org/@jest/types/-/types-26.6.2.tgz
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
npm ERR! 403
npm ERR! 403 It was specified as a dependency of '@jest/create-cache-key-function'
npm ERR! 403

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2021-05-02T06_13_29_319Z-debug.log
Install for [ 'react-native@latest' ] failed with code 1
### Logs

Please add the log output here.
[2021-05-02T07_47_35_301Z-debug.log](https://github.com/react-native-community/react-native-template-typescript/files/6410964/2021-05-02T07_47_35_301Z-debug.log)

Need help in resolving the issue .

**Comment by radko93** [comment]
Seems like this error is not related to the template. Please look on how to use the template in the readme.
