### ISSUE TITLE
can not run npx react-native init MyApp in react native CLI

### ISSUE THREAD

**Issue by Kaushallaya** [react-native-community/react-native-template-typescript#210]
## Expected results

I try to crate a new react native app and this problem appear..

## Observed results

clear the npm cash and update npm. but same problem here.. 

### Logs

× Downloading template
error Error: Command failed: npm install --save --save-exact react-native@latest
npm ERR! code E404
npm ERR! 404 Object Not Found - GET https://skimdb.npmjs.com/registry/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz - not_found
npm ERR! 404
npm ERR! 404  'remove-trailing-separator@https://skimdb.npmjs.com/registry/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Local\npm-cache\_logs\2021-07-16T15_48_17_958Z-debug.log

### System
OS: Windows 10
SDK: Android
npm: version 7.9.0

**Comment by orYoffe** [comment]
Hi @Kaushallaya  did you use the package or react-native globally before? if so please uninstall them like this
`npm uninstall -g create-react-native-web-app`
`npm uninstall -g react-native`
and then try again.

I ran the command and it worked for me

**Comment by radko93** [comment]
Seems like you are not using the template. If you have issues with React Native you can open an issue on React Native CLI repo.
