### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by GustavoMSevero** [react-native-community/react-native-template-typescript#212]
Hi guys!
I develop an app with RN, using typescript template.
When I run "build" in Xcode, it builds success, but then I run "archive" to upload the app to App Store and i get this error:
<img width="1046" alt="Captura de Tela 2021-07-26 às 19 36 37" src="https://user-images.githubusercontent.com/2678092/127181353-4f30eba1-6b9c-4df9-980a-78189c7ee958.png">

I didn't find no solution, until now to solve this problem.
Here is my macOS configuration

> System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 116.30 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by emin93** [comment]
Does this also happen when you create a vanilla project without this template?

```
npx react-native init MyApp
```

**Comment by emin93** [comment]
Closing this for now, feel free to re-open if you still encounter the issue.
