### ISSUE TITLE
[REQUEST][NEW FEATURE] Support for react native v0.65.*

### ISSUE THREAD

**Issue by hminhman** [react-native-community/react-native-template-typescript#215]
## Expected results

I know it just uploaded yesterday, but I'm really excited to work on it through TS. So can you please support for react-native 0.65.* ASAP. Thank teams so much for your support. :blush: :+1:

## Observed results

Just support for v0.64.1

## Steps to reproduce

npx react-native init AwesomeTSProject --template react-native-template-typescript

**Comment by lb90** [comment]
Someone opened a PR, which looks very good IMO: #217

**Comment by emin93** [comment]
Closing this issue as the PR https://github.com/react-native-community/react-native-template-typescript/pull/217 has been merged & released in `6.7.0`.
