### ISSUE TITLE
Does this template bundle Flipper in release?

### ISSUE THREAD

**Issue by henrymoulton** [react-native-community/react-native-template-typescript#220]
https://github.com/react-native-community/react-native-template-typescript/blob/master/template/ios/HelloWorld/AppDelegate.m#L7

In the main docs the `#ifdef FB_SONARKIT_ENABLED` is wrapped with `#if DEBUG`

https://fbflipper.com/docs/getting-started/react-native-ios#initialization

**Comment by henrymoulton** [comment]
cc @mweststrate you might have an idea

**Comment by emin93** [comment]
This is not related to this template:
https://github.com/facebook/react-native/blob/main/template/ios/HelloWorld/AppDelegate.m#L7

Please create this issue in the React Native repo, as this template aims to be consistent with the default React Native template.
