### ISSUE TITLE
Update template to match latest react-native (m1 build settings)

### ISSUE THREAD

**Issue by barbieri** [react-native-community/react-native-template-typescript#223]
In order to build on macOS with M1 (arm64), the `LIBRARY_SEARCH_PATHS` must be changed, see https://github.com/facebook/react-native/commit/a1c445a39c580037ada4a5d194a0d2daef15a25a

- do not exclude `"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64"`
- change `LIBRARY_SEARCH_PATHS` to be:
   - `"\"$(SDKROOT)/usr/lib/swift\""`
   - `"$(inherited)"`
   - `"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"`
   - **Remove:** `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`

I plan to provide a PR to do that, will just see if other, related-PR will get into RN.

**Comment by radko93** [comment]
As I mentioned in https://github.com/react-native-community/react-native-template-typescript/pull/224#issuecomment-930532831, I don't think it's a valid issue for this repo unfortunately.
