### ISSUE TITLE
Question: Should we provide Gemfile and ruby-version?

### ISSUE THREAD

**Issue by barbieri** [react-native-community/react-native-template-typescript#225]
This is more of a question than a bug report:

What do you think about providing a `Gemfile` with some recommended defaults? For instance CocoaPods 1.11 works better than 1.10 with M1 and we could state it there. It would also enable proper `bundle exec pod install`, as it would use the specified version.

While at that, we could lock the ruby version in the Gemfile and provide `.ruby-version` with some recommended version such as 2.7.4. This enables users of `rbenv` or `rvm` to use the correct version automatically. It could also avoid us to face some issues, for instance using macOS's ruby 2.6.3 with the universal build causes some issues.

I could provide a PR with those if you agree with such decision.

**Comment by radko93** [comment]
Everything you are mentioning here are great additions but are meant to be included in the `template` inside React Native core repo. Here we only pull upstream and add TS tooling.

**Comment by barbieri** [comment]
great, will talk to them to see if it's the way to go!
