### ISSUE TITLE
Command failed: yarn install

### ISSUE THREAD

**Issue by gurbela** [react-native-community/react-native-template-typescript#229]
Command: npx --ignore-existing react-native init TestApp --template react-native-template-typescript
Error: Command failed: yarn install
warning react-native > @react-native-community/cli-platform-ios > xcode > uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

I have latest version of react-native and react-native-cli

**Comment by elirangoshen** [comment]
me too

**Comment by radko93** [comment]
Please open an issue on `@react-native-community/cli`, they have to fix this.
