### ISSUE TITLE
Typescript 4.4.4 not supported by @typescript-eslint/typescript-estree

### ISSUE THREAD

**Issue by worldeggplant** [react-native-community/react-native-template-typescript#237]
## Expected results
Linting working out of the box when installing React Native with the Typescript template

## Observed results

Linting throws an error. Seems to be caused by an unsupported version of Typescript [introduced recently](https://github.com/react-native-community/react-native-template-typescript/commit/e5fce57edb5bba057105eff9bfc26dafe4aa460a).

### Logs
```
$ eslint . --ext .js,.jsx,.ts,.tsx
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.1.0

YOUR TYPESCRIPT VERSION: 4.4.4

Please only submit bug reports when using the officially supported version.
```

## Steps to reproduce

1. `$ npx react-native init --template typescript Project`
2. `$ yarn lint`

**Comment by mikehardy** [comment]
typescript is actually already on 4.5.2
template needs an update, bu thow did it go when you updated dependencies (e.g., `yarn outdated` then updating the `@typescript-esline\xyz` packages?)
