### ISSUE TITLE
Question: Release Procedure

### ISSUE THREAD

**Issue by pksorensen** [react-native-community/react-native-template-typescript#251]
HI Guys, awesome template. Thanks for you effort.

I made a fork of the project to try create my own template for a react native thing.  Is it possible that one of you would outline for me the release procedure that you use so i can reuse that also? 

I added npn token and workflows , same as yours to my github account and i basically is new to github actions.  I read the workflow as it triggers on a new release? Would that mean that you release by going to ui in github and create a new release to trigger the publish to npm ? 

Thanks for you time

**Comment by radko93** [comment]
I think we won't explain it better than the docs of Github Actions. Havee you seen those? They have examples as well: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
I'm closing this as it's not related to the package but feel fry to reply.
