### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by leotm** [react-native-community/react-native-template-typescript#261]
Lemme kno how can contribute again ^ as its been couple yrs
- https://github.com/reactwg/react-native-new-architecture/discussions/21#discussioncomment-2437885

Close to accepting a new role soon so time will become limited, no promises 😅

**Comment by leotm** [comment]
I'll continue w reviewing PRs

**Comment by radko93** [comment]
Thanks for your message. Please review PRs, answer on issues and create PRs as well if anything.
