### ISSUE TITLE
New App Screen

### ISSUE THREAD

**Issue by gamingumar** [react-native-community/react-native-template-typescript#40]
# Feature Request

Support for New App screen that came with React Native version 0.60

## Why it is needed

This template is still using the old React Native App Screen. React Native version 0.60 came with a new App screen, which is much more helpful. To make it consistent with new react native version we need to upgrade it. 

## Possible implementation

We can use same implementation as https://github.com/facebook/react-native/tree/master/Libraries/NewAppScreen with little modifications.

**Comment by emin93** [comment]
Hi and thanks for creating the issue. The changes for the new app screen have been implemented already but currently it's only in the `cli-v2` branch. Probably it makes sense to include it for the old CLI as well.

**Comment by emin93** [comment]
Version `5.1.0` now has the new app screen! 🎉
