### ISSUE TITLE
I think we need fix the devDependencies in template package.json

### ISSUE THREAD

**Issue by Matrixbirds** [react-native-community/react-native-template-typescript#44]
# Discussion & Proposal
Using stable package is very important for any one who r using this template.

# Description
I just init react native project with rn cli, And I got this package.json as below
![image](https://user-images.githubusercontent.com/9990676/60857735-35745800-a23e-11e9-83db-7554891a2dd8.png)
I think fix react native node with stable node_modules is good for developer who have no time to fix many trouble problem which could happen in setup environment.
e.g. [dependency bug](https://github.com/facebook/react-native/issues/23092#issuecomment-456380526)
I m using 0.58.0 typescript template, i think the template should be generate fixed version in devDependencies too.

**Comment by sunnylqm** [comment]
Both npm and yarn have lock files which did the "fix" thing.

**Comment by Matrixbirds** [comment]
@sunnylqm did u find some Inconsistent devDependencies from the screenshot? The 0.58 version still using @"types/react-native": "^0.60.0", I don't think it is correct, extremely using strict language like typescript.
And the lock files only working when u did generate the lock file...

**Comment by emin93** [comment]
This template doesn't support multiple RN versions, only the latest. Usually the dev dependencies are being installed as fixed versions without the caret. How did you set up the project?

**Comment by emin93** [comment]
I'm closing this issue for now because I think it's related to https://github.com/react-native-community/react-native-template-typescript/issues/42.
