### ISSUE TITLE
CocoaPods install fails: url_for_request: uninitialized constant GhInspector::Sidekick::ERB (NameError)

### ISSUE THREAD

**Issue by l-Marty-l** [react-native-community/react-native-template-typescript#53]
# Bug

After creating the project successfully, `pod install` seem to fail. First I got `Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa`, which I could solve following this post: https://github.com/CocoaPods/CocoaPods/issues/7835#issuecomment-407428465

After that I got the error

```
/Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:67:in `url_for_request': uninitialized constant GhInspector::Sidekick::ERB (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:24:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	from /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod:22:in `load'
	from /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod:22:in `<main>'
```

after re-trying `pod install` on the iOS project. `gem update xcodeproj` didn't help. The only hint I have is this: https://github.com/CocoaPods/CocoaPods/issues/7478 but it got closed without being addressed and I don't know how to continue, right now.

## Environment info

React native info output:

```sh
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 353.47 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 19, 22, 23, 24, 25, 26, 28
      Build Tools: 25.0.2, 26.0.2, 27.0.3, 28.0.0, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react-native: ^0.60.4 => 0.60.4
```

react-native 0.60.4
react-native-typescript-template 5.2.0

## Steps To Reproduce

```sh
npm i react-native react-native-template-typescript -D
npx react-native init app --template react-native-template-typescript@next
cd app/ios
pod install
```

**Comment by radko93** [comment]
Does it work for you without typescript template?

**Comment by l-Marty-l** [comment]
> Does it work for you without typescript template?

I'm sorry, I don't know. I decided to move on and use the `expo-cli` to setup my project, instead. It might have more limits, but it just works. It's perfect for my needs nonetheless.

**Comment by radko93** [comment]
I will close this then.

**Comment by l-Marty-l** [comment]
Personally, I'm fine with that, but you should not lock this issue, so others can request to re-open it, in case they have the same issue. Thanks!

**Comment by charles161** [comment]
i'm facing the same issue

**Comment by chandniKkpl** [comment]
I am also facing this issue. Has anyone a solution for it?

**Comment by chandniKkpl** [comment]
I found the solution just remove the pod and install it again and it is working fine. These steps I used, 

Install clean:

$ sudo gem install cocoapods-clean
Run deintegrate in the folder of the project:

$ pod deintegrate

Clean:

$ pod clean

Modify your podfile (delete the lines with the pods you don't want to use anymore) and run:

$ pod install
