### ISSUE TITLE
npx react-native init MyApp --template react-native-template-typescript does not work correctly

### ISSUE THREAD

**Issue by ajaymore** [react-native-community/react-native-template-typescript#64]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.15 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Library version: x.x.x

## Steps To Reproduce

1. After running command `npx react-native init MyApp --template react-native-template-typescript` I get below error in terminal
<img width="907" alt="Screenshot 2019-09-12 at 6 27 53 PM" src="https://user-images.githubusercontent.com/7659804/64786312-cbed2e80-d58b-11e9-9c53-8797889ecae6.png">
The installer is looking for package **react-native-template-react-native-template-typescript** which is not available.

##

2. After removing react-native-template- & running command `npx react-native init MyApp --template typescript` I get below folder structure which is incorrect.
<img width="328" alt="Screenshot 2019-09-12 at 6 30 00 PM" src="https://user-images.githubusercontent.com/7659804/64786467-17074180-d58c-11e9-9857-72aa61fcbbc6.png">
Typescript project is created inside template directory.

**Comment by mrbrentkelly** [comment]
Thank you @eugenemlee that worked for me 👍. I've submitted a PR which updates the README accordingly https://github.com/react-native-community/react-native-template-typescript/pull/65.

**Comment by ajaymore** [comment]
how do we run `react-native run-android` after doing `npm uninstall -g react-native-cli`

**Comment by eugenemlee** [comment]
@ajaymore use `yarn react-native run-android` or create a script in package.json

**Comment by ajaymore** [comment]
> @ajaymore use `yarn react-native run-android` or create a script in package.json

<img width="972" alt="Screenshot 2019-09-13 at 5 57 48 PM" src="https://user-images.githubusercontent.com/7659804/64862396-09b38b00-d650-11e9-9079-526134a48ab5.png">
Something has gone wrong. I can't understand what.

**Comment by eugenemlee** [comment]
See [here](https://github.com/facebook/react-native/issues/25629#issuecomment-511209583) for the solution.

**Comment by ajaymore** [comment]
Thank you @eugenemlee. Putting down all the steps for those who might visit this issue.

1. Uninstall Global react-native-cli 
```
npm uninstall -g react-native-cli
```
2. Create The App with Typescript template
```
npx react-native init MyApp --template react-native-template-typescript
```
3. Generate debug.keystore in `android/app/` directory
```
keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
```
4. Run below command to launch the app in emulator.
```
yarn react-native run-android
```

**Comment by ivanbtrujillo** [comment]
> run
```
npx react-native run-android 
```
