### ISSUE TITLE
Default tsconfig.json missing

### ISSUE THREAD

**Issue by jarmali** [react-native-community/react-native-template-typescript#70]
Default tsconfig.json is missing from template. Adding it will make configuring Typescript options a lot easier for developer.

See example: https://github.com/microsoft/TypeScript-React-Native-Starter/blob/master/ExampleProject/tsconfig.json.

**Comment by radko93** [comment]
Feel free to submit a PR if you want to have it quicker :)

**Comment by emin93** [comment]
Be aware, this will only fix type checking and has no impact on transpilation. As TypeScript transpilation is handled by Babel, you have to do configuration in the `babel.config.js`.

**Comment by dcipher00** [comment]
Is it okay if I work on this issue?

**Comment by radko93** [comment]
@dcipher00 feel free :)

**Comment by dcipher00** [comment]
@radko93 I have raised the PR for this issue, could you please review and let me know in case anything needs to be changed
