### ISSUE TITLE
Cannot find name 'global'.ts(2304)

### ISSUE THREAD

**Issue by codler** [react-native-community/react-native-template-typescript#71]
Im getting `Cannot find name 'global'.ts(2304)` typescript error in App.tsx at global.HermesInternal. Im using VS code.

**Comment by emin93** [comment]
That's because of missing type definitions in `@types/react-native` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/globals.d.ts). If someone wishes to fix it, you could create a PR there and as soon as there's a new version, I'll include it in the template 🙂

**Comment by sudeepto-dutta** [comment]
@radko93  I have already bootstrapped my project using version `6.3.0` . How can I update this package without bootstrapping a new project ?

**Comment by radko93** [comment]
@sudeepto-dutta you can copy this file if you want https://github.com/react-native-community/react-native-template-typescript/blob/master/template/App.tsx. But you can just remove the Hermes from you App.tsx (you don't need it).
