### ISSUE TITLE
Incomplete Usage docs

### ISSUE THREAD

**Issue by thiagobrez** [react-native-community/react-native-template-typescript#73]
# Question

In order to make the init command work (`npx react-native init MyApp --template react-native-template-typescript`), I also had to uninstall react-native-cli globally from yarn (`yarn global remove react-native-cli`), otherwise the command would fail accusing the following:

`error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found"`

`error This module isn't specified in a package.json file.`

Also, when trying to run the app, I had to use the packaged react-native from the project (`$(yarn bin)/react-native run-ios`), as the globally installed `react-native-cli` was removed, when following the docs.

**Comment by MateusAndrade** [comment]
Hi @thiagobrez , please have a look at #65. The last version on the master and npm already have a warning about that. Btw, thanks for helping us with that.

**Comment by thiagobrez** [comment]
Hi @MateusAndrade! Thanks for the feedback. But maybe I've not expressed myself correctly. I see that in the latest master version there is a warning about removing `react-native-cli` from `npm`, but not `yarn`. What I was trying to state was that one needs to remove the package globally from **both** package managers. At least, that's what worked for me. 

Thanks for this great package!

**Comment by emin93** [comment]
You can do `npx react-native run-ios`. If you wish to not use `npx`, you can also install the new CLI globally `npm i -g @react-native-community/cli` or `yarn global add @react-native-community/cli`.
