### ISSUE TITLE
some about legagy cli 

### ISSUE THREAD

**Issue by GreatAuk** [react-native-community/react-native-template-typescript#79]
README.md:
![image](https://user-images.githubusercontent.com/20253809/65738343-0b7f5300-e114-11e9-9b61-56c1dd8c4d04.png)

React Native official doc 0.61:
![image](https://user-images.githubusercontent.com/20253809/65738349-13d78e00-e114-11e9-9541-13edac2121f7.png)
![image](https://user-images.githubusercontent.com/20253809/65738450-74ff6180-e114-11e9-8326-15b168567179.png)

**Comment by radko93** [comment]
Thanks for reporting that. This definitely outdated on RN docs side. I will close this issue and try to resolve it there.
