### ISSUE TITLE
How to use this template for a RN 0.59 app

### ISSUE THREAD

**Issue by luisnaranjo733** [react-native-community/react-native-template-typescript#82]
# Question

The docs include the following information for RN 0.60 and 0.61

> 
> react-native@0.61.0 or higher
> 
> npx react-native init MyApp --template react-native-template-typescript
> react-native@0.60.x
> 
> npx react-native init MyApp --template react-native-template-typescript@6.2.0

But how would you use this template for a RN 0.59 app? I know it seems odd to want to bootstrap a new app with an older version of RN, but it can be useful for library maintainers who want to keep a matrix of RN versions in their samples\ to demonstrate compatibility of their library across recent versions of RN. With the current docs, it's unclear how to do it. I've been trying to use this template but the CLI doesn't seem to be applying it correctly because I end up with an App.js

**Comment by luisnaranjo733** [comment]
Just figured out why this isn't working after uninstalling npm and yarn global react-native CLIs

npx react-native init Rn59SampleApp --template react-native-template-typescript --version 0.59.10
error Cannot use React Native CLI to initialize project with version lower than 0.60.0.

**Comment by gianpaj** [comment]
If anybody needs to install 0.59.x do this:

```
mkdir rn59cli
cd rn59cli
npm init -f
npm install react-native-cli
node_modules/.bin/react-native init Rn59SampleApp --version 0.59.10
```

```
Using yarn v1.21.1
Installing react-native@0.59.10...
yarn add v1.21.1
warning ../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
info Direct dependencies
└─ react-native@0.59.10
```
```
cat Rn59SampleApp/package.json
{
  "name": "Rn59SampleApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.10"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "babel-jest": "^25.1.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
