### ISSUE TITLE
Init command not working at all

### ISSUE THREAD

**Issue by cargallo** [react-native-community/react-native-template-typescript#85]
# Bug

![image](https://user-images.githubusercontent.com/13320290/66152604-3247f880-e5f0-11e9-8378-40d1b9598a36.png)

## Environment info

no react-native-cli installed 

## Steps To Reproduce

Just following Readme documentation

Describe what you expected to happen:

I wanted a new project created with typescript support

**Comment by radko93** [comment]
Have you tried to uninstall the CLI anyway? This worked for me but on Mac.

**Comment by cargallo** [comment]
@radko93 I printed at the begining the react-native command to show that I had uninstalled it in both yarn and npm

**Comment by radko93** [comment]
Can you check in the temp folder if the missing file exists there? And also if `tsConfig` is there, this would mean you use latest version.

**Comment by cargallo** [comment]
The entire folder rncli-init-template.... doesn't exists. Also I tried to create a Simple project without --template and doesn't work neither. 
react-native init MyApp... folder doesn't created too.

**Comment by radko93** [comment]
If you cannot create a project without template then file open at https://github.com/react-native-community/cli and they will be able to help more than me.

**Comment by cargallo** [comment]
I hope the reason is that I Google is sending spies to boycott RN. Because not being able to start a project after 4+ years of platform existence is far away from being credible. Sounds like we are calling releases candidates to pre-alpha ones

**Comment by karmil32** [comment]
I have the same issue. Two weeks ago I created project with this command without any problem (and it's still working). But now i can't create new one

**Comment by cargallo** [comment]
I can't believe that this problem is still an issue. This is the most basic feature of the entire platform, making a new project from scratch, and it's not working. Unbelievable!

**Comment by ameernormie** [comment]
This template only works with the new CLI. Make sure you have uninstalled the legacy react-native-cli first (npm uninstall -g react-native-cli), for the above command to work. If you wish to not use npx, you can also install the new CLI globally (npm i -g @react-native-community/cli or yarn global add @react-native-community/cli).

#### react-native@0.61.0 or higher
npx react-native init MyApp --template react-native-template-typescript

#### react-native@0.60.x
npx react-native init MyApp --template react-native-template-typescript@6.2.0
