### ISSUE TITLE
How to use typescript template for RN app < 0.60

### ISSUE THREAD

**Issue by lucianomlima** [react-native-community/react-native-template-typescript#88]
# Question

I try several commands before open this issue. #82 doesn't have any guide to how to use for RN apps below 0.60.

I try:

- react-native init Example --version 0.59.10 --template https://github.com/react-native-community/react-native-template-typescript@5.2.1
- react-native init Example --version 0.59.10 --template https://github.com/react-native-community/react-native-template-typescript/tree/legacy
- react-native init Example --version 0.59.10 --template typescript@5.2.1
- react-native init Example --version 0.59.10 --template typescript@legacy
- react-native init Example --version 0.59.10 --template typescript
- react-native init Example --version 0.59.10 --template react-native-template-typescript

Tried with `npx react-native init...` as well and can't find any solution for this.
Any help how I can create an new app with RN@0.59.10 and typescript I appreciate.

**Comment by radko93** [comment]
Hey,
You would need to find the template version (check releases) that was made for RN 0.59 and then try either with npx or just normal react-native init. If this won't work you need to create a normal project and manually add typescript dependencies (there is official react native doc about it) or create 0.60 empty app and copy some things from there.
