### ISSUE TITLE
init template dont create tsconfig

### ISSUE THREAD

**Issue by Knjaz89** [react-native-community/react-native-template-typescript#91]
# Bug

after executing the command, the file tsconfig is not created

## Environment info

React native info output:

```
System:
    OS: macOS 10.15
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
```

## Steps To Reproduce

npx react-native init testProj --template react-native-template-typescript

Describe what you expected to happen:

1. create project files
2. create tsconfig.json / esconfig.json

**Comment by MateusAndrade** [comment]
You can give a try with the master version? #83 added a tsconfig.json.

**Comment by Knjaz89** [comment]
> You can give a try with the master version? #83 added a tsconfig.json.

how to do it?
npx react-native init MyApp --template react-native-template-typescript@master ?

**Comment by MateusAndrade** [comment]
@Knjaz89 you can give a look here: https://github.com/react-native-community/cli/blob/master/docs/init.md#initializing-project-with-custom-template. Btw, i dont find a way to use the master version when creating a new project 😅

**Comment by byteasc** [comment]
`npx react-native init MyApp --template react-native-template-typescript`

This actually fails for me as it ends up looking for `react-native-template-react-native-template-typescript`. I had to use `--template typescript` . and it was able to pull it down and worked okay. It did fail to copy the template though and instead just put it in a folder named template (but was easy enough to copy everything out of it into the root)

**Comment by radko93** [comment]
@byteasc if you need to use `--template typescript` you have old CLI installed. See readme.

**Comment by byteasc** [comment]
> @byteasc if you need to use `--template typescript` you have old CLI installed. See readme.
@radko93 
Now im getting this from what appears to be the new cli 
`✔ Downloading template
✖ Copying template
error RangeError: Maximum call stack size exceeded
`

**Comment by radko93** [comment]
@byteasc does `npx react-native init MyApp --template react-native-template-typescript@6.3.4` change anything or `npx react-native --ignore-existing init MyApp --template react-native-template-typescript@6.3.4`

**Comment by byteasc** [comment]
> @byteasc does `npx react-native init MyApp --template react-native-template-typescript@6.3.4` change anything or `npx react-native --ignore-existing init MyApp --template react-native-template-typescript@6.3.4`

@radko93  I got it working finally, had to just uninstall everything I had related to react-native and clean out npm cache, as well, and it finally started working as expected (so far). Thank you!

**Comment by byteasc** [comment]
I did get same issue as @Knjaz89  though where tsconfig.json isn't created/copied in

**Comment by radko93** [comment]
`tsConfig.json` was in a wrong directory (it was fixed but the commit was not released), https://github.com/react-native-community/react-native-template-typescript/releases/tag/6.3.5 should fix it.

**Comment by ataravati** [comment]
@radko93 I'm having the same issue. Not only `tsConfig.json` is not created, I don't have an `App.ts` either.

**Comment by radko93** [comment]
@ataravati and in package.json do you have the changes from template?

**Comment by ataravati** [comment]
> @ataravati and in package.json do you have the changes from template?

No. And, I just realized that I get this error at the end.

>error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/aliyar/MyApp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.21.1
[1/2] 🗑  Removing module react-native-template-react-native-template-typescript@6.3.4...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript@6.3.4. This is not a critical error, you can work on your app.
(node:33868) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript@6.3.4
    at makeError (/Users/aliyar/MyApp/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/aliyar/MyApp/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:33868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:33868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
