### ISSUE TITLE
Unable to import another tsx files in to App.tsx

### ISSUE THREAD

**Issue by varmab** [react-native-community/react-native-template-typescript#93]
Here is my App.tsx

import React from 'react';
import { View, Text} from 'react-native'

import HomeScreen from 'screens/home/HomeScreen';

const App = () => {
  return (<HomeScreen/>)
};

export default App;

I am getting this error when starting app

Unable to resolve module `screens/home/HomeScreen` from `App.tsx`: screens/home/HomeScreen could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

Any ideas what is missing?

**Comment by varmab** [comment]
I figured it is issue with visual studio code auto import optiion. It didn't put ./ infront of path causing an issue. Not sure why Auto Import not working correctly in this case.

**Comment by nighttiger1990** [comment]
I got same. Did you know the reason and resolve?

**Comment by victorwpbastos** [comment]
@nighttiger1990 I resolved this putting this line in VS Code Settings:

```json
"typescript.preferences.importModuleSpecifier": "relative",
```
