### ISSUE TITLE
Typescript 3.7.x support

### ISSUE THREAD

**Issue by oferRounds** [react-native-community/react-native-template-typescript#99]
Hi!

Hope it’s a legitimate question – probably I miss something silly :(
 
I wanted to try out a new project with the Typescript (3.7.2), with optional chaining and more. I followed the instructions on React Native website, but optional chaining doesn’t seem to work

My end goal is to upgrade my existing project (I have upgraded there to 3.7.2, but still doesn’t work)

What am I missing?

Would love for your help
Thank you!

**Comment by radko93** [comment]
@oferRounds Unfortunately we don't support dynamic versions right now, you need to upgrade manually after you create a project. I did not test new Typescript yet. If you can test it feel free to submit a PR if everything works :)

**Comment by codler** [comment]
What error do you get?

**Comment by oferRounds** [comment]
@radko93 sorry for the delay (for some reason the reply arrived on my spam), anyhow – got you, and thanks for the reply!

**Comment by oferRounds** [comment]
@codler thanks! I don’t have the error available now – I moved on a bit – but once I try again I’ll post it here

**Comment by josephmbeveridge** [comment]
Posted a PR for upgrading the template to 3.7.3 and confirmed that it works with optional chaining without any errors.
